### ISSUE TITLE
testing for Backbone.PageableCollection instanceof Backbone.Collection returns false

### ISSUE THREAD

**Issue by pardo-bsso** [backbone-paginator/backbone-pageable#109]
Hi,

we are using Pageable together with Backbone.Relational. Inside Relational there are many tests that check if an object or its prototype is either an instance of a Backbone Model or Collection. If I try to use Pageable on top of that it fails.

We are using: 
Pageable version 1.3.2
Relational version: 0.8.5

**Comment by dhruvaray** [comment]
@wyuenho +1 for fixing this.

**Comment by wyuenho** [comment]
Backbone.PageableCollection _IS_ an instance of Backbone.Collection.

https://github.com/wyuenho/backbone-pageable/blob/1.3.2/lib/backbone-pageable.js#L105

As I don't use Backbone.Relational, it's going to be hard for me to fix this without anymore info.

**Comment by dhruvaray** [comment]
@wyuenho : It does not have anything to do with Backbone-Relational. (Though the description of the bug says so) See this screenshot from the bb-pageable demo app and the output in Firebug console

![backbone pageable](https://f.cloud.github.com/assets/2075506/999467/6d0a50f0-0a30-11e3-97ad-a312ef8810a9.png)

Even though you are extending Backbone.Collection, it may have something to do with the over-ride of the constructor property at 
https://github.com/wyuenho/backbone-pageable/blob/1.3.2/lib/backbone-pageable.js#L257

**Comment by wyuenho** [comment]
Ohhhh OK. I guess I just have to make a surrogate and juggle around the prototypes again then. Thanks!

**Comment by dhruvaray** [comment]
No problems... Glad I could help. The fix is important otherwise it will trip up a lot of folks and plug-ins...

**Comment by dhruvaray** [comment]
As a side note, our new [Backbone Debugger](http://dhruvaray.github.io/spa-eye/) works nicely with Backbone-pageable too!

![backbone-pageable-eye](https://f.cloud.github.com/assets/2075506/1000069/cc519a30-0a41-11e3-98af-f8cf93f839b2.png)

**Comment by pardo-bsso** [comment]
Thanks guys you rock!

**Comment by wyuenho** [comment]
Oh whoa this debugger is awesome!

**Comment by josx** [comment]
@wyuenho +1 for fixing this

In many backbone plugins including backbone-relational,backbone-associations there are checks with instanceof:

```
Collection instanceof Backbone.Collection
false
```

Right now with a Collection extending from Backbone.PageableCollection gives false.

**Comment by dhruvaray** [comment]
@wyuenho : Thanks for the appreciation! I hope folks start using it for their regular Backbone work

**Comment by wyuenho** [comment]
If anyone can be so kind as to submit a PR for this before I get to it, it'll be great.

**Comment by wyuenho** [comment]
OMG ROFLMFAO this is just plain stupid I can't believe all 4 of us are confused about how `instanceof` in JS works. We probably have decades of experience combined and we still missed it.

@pardo-bsso @dhruvaray @josx Backbone.PageableCollection is right. You are wrong. Don't believe me? Try this in your console:

```

> var A = function () {};
> var B = function () {};
> B.prototype = new A;
> B instanceof A
false

> var b = new B
> b instanceof B
true

> b instanceof A
true
```

Look, the `instanceof` operator in Javascript is not the same as Java. In Java, a subclass of a superclass is an instance of the superclass, in Javascript, an instance is considered an object instance only if it had been constructed by invoking `new` because it essentially makes a copy of the prototype and assign it to `__proto__`. That's how JS looks up a prototype chain. A new constructor (A and B in this case) is only an instance of `Function`. To have B to be an instance of A, you'll have to do this:

``` javascript
> B.__proto__ = new A
> B instanceof A
true
```

`__proto__` is non-standard but it's pretty much everywhere. Backbone's `extend` doesn't assign to `__proto__` for safety reasons. To solve this, you need an equivalent of Python's `issubclass` function, which will basically recursively traverse up the `__super__` property of a constructor and compare it will `Backbone.Collection.prototype`.

``` javascript
function subclassof(t1, t2) {
  var parent = t1.__super__;
  while (parent) {
    if (parent == t2.prototype) return true;
    parent = parent.__super__;
  }
  return false;
}
```

_Update_:

Alternatively, this might be a good proxy:

``` javascript
t1.prototype instanceof Backbone.Collection
```

Both Backbone.Relational and Backbone.association need to do this, which I think they already do...

http://dailyjs.com/2012/11/26/js101-proto/
http://coderkeen.com/old/articles/proto.html
http://stackoverflow.com/questions/650764/how-does-proto-differ-from-constructor-prototype
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto

**Comment by dhruvaray** [comment]
This is a non-bug! In fact all the 3 libraries - Pageable, Associations, Relational - are good in respecting this!

``` javascript
//In the console
new Backbone.AssociatedModel instanceof Backbone.Model //true
new Backbone.AssociatedModel instanceof Backbone.AssociatedModel //true
```

**Comment by wyuenho** [comment]
Yes @dhruvaray you are right!

**Comment by dhruvaray** [comment]
@wyuenho : I typed up the wrong comparison in the console screenshot - which led to this confusion. My bad and apologies for your wasted time :( . (Reminder for me : Don't multi-task too much!)

**Comment by wyuenho** [comment]
Only took me an hour :)

See I knew this and then after a fews months of Scala I've forgotten about it.
