### ISSUE TITLE
Sort mapping and query params suggestion

### ISSUE THREAD

**Issue by conorjpower** [backbone-paginator/backbone-pageable#115]
Hi,
   I have been using PageableCollection for a while now and have a comment / suggestion about one aspect which was not as intuitive as other parts.

In my situation I have a BaseCollection extending from PageableCollection, which sets the query parameters and the mapping e.g.:

```
    ...
    queryParams: {

        currentPage: "page",
        pageSize: "rows",
        sortKey: "sidx",
        order: "sord"
    }
    ...
```

I then have collections which extend from this and when they are to be used I have been inclined to use them as follows:

```
    ...
    var list = new MyCollection([], {
            queryParams: {
                sidx: "expectedStartDate",
                sord: "asc",
                filters: JSON.stringify(allFiltersJSON)
            }
        });
```

Where I can set the default sort parameters and some additional filter parameters that are used. The issue here, as you're probably well aware is that this overrides the original queryParams so the mapping for the sort params are lost. To get around this I would have to pass the full query string definition when using it or revert to this: 

```
    ...
    var list = new MyCollection();
        list.queryParams.sidx = "expectedStartDate";
        list.queryParams.sord = "desc";
        list.queryParams.filters =  JSON.stringify(unverifiedFiltersJSON);
```

Having to call it this way is counter intuitive I feel, more error prone and less encapsulated. Ideally I'd like to be able to pass my query string params without impacting the mapping fields.

Perhaps the mapping field is best defined separate from the queryParams.

It seems that

**Comment by wyuenho** [comment]
You can do this as well:

``` javascript
var list = new MyCollection([], {
  queryParams: _.defaults({
    sidx: "expectedStartDate",
    sord: "asc",
    filters: JSON.stringify(allFiltersJSON)
  }, MyCollection.prototype.queryParams);
});
```

I'm afraid it's too late to change it now. It'll break many existing apps. pageable is merging with paginator, so when the next major version comes around, I may consider this, but it's not that hard to get around this for now.

**Comment by wyuenho** [comment]
I think this is somewhat misleading because while the `BaseCollection.prototype.queryParams` seems like it's replacing the `Pageable.prototype.queryParams`, (which it is) when you invoke `BaseCollection.prototype.constructor`, as long as you have not overridden it without calling `PageableCollection.prototype.constructor` it will always [merge](https://github.com/wyuenho/backbone-pageable/blob/master/lib/backbone-pageable.js#L288) in `PageableCollection.prototype.queryParams` and `BaseCollection.prototype.constructor`. You can confirm this in the console actually. So I think the case you described with custom `queryParams` being lost shouldn't happen.

``` javascript
> var p = Backbone.PageableCollection.extend({ queryParams: {"a": 1} });
  undefined
> p.prototype.queryParams;
  Object {a: 1}
> (new p([], { queryParams: {b: 2} }).queryParams;
  Object {currentPage: "page", pageSize: "per_page", totalPages: "total_pages", totalRecords: "total_entries", sortKey: "sort_by", a: 1, b: 2, ...}
```

I do admit that this is too much magic that probably leads you to think BaseCollection.prototype.queryParams will have been merged there. That's certainly possible but that would require a completely warp people's usual understanding of how virtual inheritance works, and worse, it requires a custom `.extend` static method.
