### ISSUE TITLE
model sets pageable collection as its collection

### ISSUE THREAD

**Issue by jurgenkalverboer** [backbone-paginator/backbone-pageable#128]
when you add a model to your pageable collection:

myPageableCollection.add({}, {at:0});

The new model will set the pageableCollection as its collection and not the fullCollection.

When you switch pages the pageableCollection is destroyed and a new one is created. The refference to the collection in the model is thus not correct anymore. When you try to use the collection attribute within the model you get a null pointer exception.

**Comment by wyuenho** [comment]
Actually the model will be inside the top-level pageable collection and the full collection at the same time.

The `Backbone.Model#collection` attribute is not reliable, never was and never will be because it makes a very strange assumption that your model reference will only ever belong in one collection at a time. Pageable tries very hard to hide that from you but will still leak from time to time.

I think the best way to get around this issue is to ask yourself why you'll want to get back the collection reference from a model. I don't know of a single language where you can get a reference to the parent collection from an element.

If you can, I think the best way is to keep the collection references around and query whether the model is inside the collections.

Let me know if this doesn't solve your problem.

**Comment by jurgenkalverboer** [comment]
I was already not sure if it was a feature or a bug. I can solve my problem with a different approach. Thanks for your fast and usefull reply
