### ISSUE TITLE
getPage doesn't set correctly currentPage in client mode

### ISSUE THREAD

**Issue by borys-kupar** [backbone-paginator/backbone-pageable#154]
Hi,
I have MyPageableCollection which mode is "client". When this collection is retrieved the first time, state.currentPage is incorrect.

Example:

``` javascript
var items = new MyPageableCollection();
items.getPage(3, {fetch: true});
```

So, it retrieved my collection and **items.models** contains 2 models from 3rd page what is correct. But **items.state.currentPage** is 1, what is incorrect, because it has to be 3.

p.s:
I tried to set currentPage parameter in constructor, but the result is the same.

Thanks!

**Comment by wyuenho** [comment]
It is actually correct.

Client mode pagination works with the assumption that all the data will have been bootstrapped into your collection before pagination happens. When you force a fetch it will only fetch the models for that page. You items collection is initially empty, so when you issue the first fetch, whatever comes down is treated as the first page, it doesn't matter which page you are actually fetching, otherwise pageable will have to pad the collection with some dubious filler objects.

Just use server mode if you want to fetch page by page.
