### ISSUE TITLE
Suggestion:  infinite mode reset method

### ISSUE THREAD

**Issue by gaisho** [backbone-paginator/backbone-pageable#157]
Please consider my humble contribution.

Perhaps it can be useful to have a method that resets the data of fullCollection after fetching new data in infinite mode.

For instance, I have an infinite collection with several pages and it works perfect with `getNextPage()`. 

However  when I call `mycollection.getFirstPage()`, it doesn't remove the data from the fullCollection and replace it with fresh data from the server; instead the data that is fetched is appended to the existing list.  This forces me to first call `mycollection.fullCollection.reset()` before I call `mycollection.getFirstPage()`.

I tried to do this:  `mycollection.getFirstPage({reset:true})` but this doesn't seem to resolve it.

Great plugin.  Awesome Support.  
Thanks.

**Comment by wyuenho** [comment]
You can force a refetch with collection.getFirstPage({fetch: true});

**Comment by gaisho** [comment]
I tried that.  The data is fetched yes but the results are appended to fullCollection instead of resetting the fullCollection.  So I end up with old data and new data in the fullCollection instead of just the new data.

that's why i have to run `collection.fullCollection.reset()` first.

**Comment by wyuenho** [comment]
Appending will only happen when you have different ids, otherwise the old results on the first page will just get updated.

Why would you expect getFirstPage under infinite paging when the first page has already been fetched to reset fullCollection by default? If you must, just call fetch({reset: true})

**Comment by gaisho** [comment]
My situation is that I have categories which I use to filter some of the data.
So my first URL to fetch data is `domain.com/api/get_posts/` for example.  

Then somewhere the user may choose to filter using a category, which forces me to change the url to `domain.com/api/get_posts/?cat=x`.  

If I do it as shown below, the new data is appended to the existing data (which is what I don't want): 

```
collection.queryParams.cat = x;
collection.getFirstPage({fetch:true})
```

Therefore I'm forced to call `collection.fullCollection.reset()` first to flush the existing data and only then fetch the new data.

My suggestion is that perhaps we should have a method to fetch new results which would replace the current data completely.  Just to reduce boiler plate.  I suppose it's also intuitive that if you fetch new data on the first page, the collection must have ONLY the new data and nothing else.

**Comment by wyuenho** [comment]
The identity of a model within a backbone collection is determined solely from its id if there's one. Which URL you use to fetch the models has no play in this. The problem is clearly that the same blog posts fetched from different URLs having different ids. If that's the case, you are modeling your entities wrong. If a model having an ids that's the same as a model within the collection, the default behavior is a merge.

**Comment by stanch** [comment]
@vusisindane For the record, I had exactly the same problem. After reading the source code, I ended up with this, which seems to do the trick:

``` javascript
// this resets fullCollection without firing an extra “reset” event
collection.switchMode('server', { fetch: false });

// go back to “infinite” mode and refetch the first page
collection.switchMode('infinite', { fetch: true, resetState: true }); 
```
