### ISSUE TITLE
Comparator definition redundancy

### ISSUE THREAD

**Issue by gbedardsice** [backbone-paginator/backbone-pageable#89]
When using `Backbone.Pageable` in client mode with `Backgrid`, I found that if I wanted to replace the default comparator function, I had to override it at two places. [Here](https://github.com/wyuenho/backbone-pageable/blob/master/lib/backbone-pageable.js#L1218) and [here in Backgrid](https://github.com/wyuenho/backgrid/blob/master/src/header.js#L94).

This seems odd to me. Is there any reason `setSorting` could not take a `comparator` or even a `makeComparator` option?

**Comment by wyuenho** [comment]
You generally don't need to override `_makeComparator`. `setSorting` is a convenient function that will create a comparator and set it to the collection for you.

I'm curious tho, what problem is the default behavior causing you that you need to override the default comparator?

**Comment by gbedardsice** [comment]
I'm using a [natural sort](https://github.com/kvz/phpjs/blob/master/functions/strings/strnatcasecmp.js) comparator. I know I should probably rely on server side paging for this type of operation, but right now it's not possible for me.

**Comment by wyuenho** [comment]
Sometime I wish JS had operator overloading :)

I didn't anticipate this use case and I just assumed whatever you are sorting on will have a natural order comparable by the language's default comparison operators.

Another reason is that in the case the collection is not a pageable collection, a comparator will need to be generated and attached to the collection.

Lastly, the reason `setSorting` doesn't take a comparator is because besides setting a comparator to the collection, I also need to know the order in order to change state.order. I wouldn't know that just by looking at the comparator.

**Comment by wyuenho** [comment]
So I think if you are using backgrid and pageable, and need to supply your own comparator, you pretty much have to override it in 2 places.

**Comment by gbedardsice** [comment]
Yeah, it is tricky. Thanks for answering.
