### ISSUE TITLE
how can i put a "Show all" to render all elements

### ISSUE THREAD

**Issue by echeypaz** [backbone-paginator/backbone-pageable#97]
hi, can i extend paginator to show all elements from collection, adding a "show all", on the rigth >> element?

Thanks.

**Comment by wyuenho** [comment]
Hi,

I think you must have confused this repository with

https://github.com/wyuenho/backgrid-paginator.

But to answer your question, yes you may do that tho from UI standpoint it can be weird because all of a sudden I go from 10 pages to 1 really long page. If you really want to do that, you may extend Backgrid.Extension.Paginator. Inside your event handler, you may call pageableCollection#setPageSize(collection.state.totalRecords).

**Comment by echeypaz** [comment]
Thanks, It's Works. :)
